# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T13:28:14+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Header, Path
from pydantic import SecretStr, conint, constr

from models import (
    EndpointsEndpointNameInvocationsPostRequest,
    InternalDependencyException,
    InternalFailure,
    InvokeEndpointAsyncOutput,
    InvokeEndpointOutput,
    ModelError,
    ModelNotReadyException,
    ServiceUnavailable,
    ValidationError,
)

app = MCPProxy(
    contact={
        'email': 'mike.ralphson@gmail.com',
        'name': 'Mike Ralphson',
        'url': 'https://github.com/mermade/aws2openapi',
        'x-twitter': 'PermittedSoc',
    },
    description=' The Amazon SageMaker runtime API. ',
    license={'name': 'Apache 2.0 License', 'url': 'http://www.apache.org/licenses/'},
    termsOfService='https://aws.amazon.com/service-terms/',
    title='Amazon SageMaker Runtime',
    version='2017-05-13',
    servers=[
        {
            'description': 'The Amazon SageMaker Runtime multi-region endpoint',
            'url': 'http://runtime.sagemaker.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Amazon SageMaker Runtime multi-region endpoint',
            'url': 'https://runtime.sagemaker.{region}.amazonaws.com',
            'variables': {
                'region': {
                    'default': 'us-east-1',
                    'description': 'The AWS region',
                    'enum': [
                        'us-east-1',
                        'us-east-2',
                        'us-west-1',
                        'us-west-2',
                        'us-gov-west-1',
                        'us-gov-east-1',
                        'ca-central-1',
                        'eu-north-1',
                        'eu-west-1',
                        'eu-west-2',
                        'eu-west-3',
                        'eu-central-1',
                        'eu-south-1',
                        'af-south-1',
                        'ap-northeast-1',
                        'ap-northeast-2',
                        'ap-northeast-3',
                        'ap-southeast-1',
                        'ap-southeast-2',
                        'ap-east-1',
                        'ap-south-1',
                        'sa-east-1',
                        'me-south-1',
                    ],
                }
            },
        },
        {
            'description': 'The Amazon SageMaker Runtime endpoint for China (Beijing) and China (Ningxia)',
            'url': 'http://runtime.sagemaker.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
        {
            'description': 'The Amazon SageMaker Runtime endpoint for China (Beijing) and China (Ningxia)',
            'url': 'https://runtime.sagemaker.{region}.amazonaws.com.cn',
            'variables': {
                'region': {
                    'default': 'cn-north-1',
                    'description': 'The AWS region',
                    'enum': ['cn-north-1', 'cn-northwest-1'],
                }
            },
        },
    ],
)


@app.post(
    '/endpoints/{EndpointName}/async-invocations#X-Amzn-SageMaker-InputLocation',
    description=""" <p>After you deploy a model into production using Amazon SageMaker hosting services, your client applications use this API to get inferences from the model hosted at the specified endpoint in an asynchronous manner.</p> <p>Inference requests sent to this API are enqueued for asynchronous processing. The processing of the inference request may or may not complete before you receive a response from this API. The response from this API will not contain the result of the inference request but contain information about where you can locate it.</p> <p>Amazon SageMaker strips all <code>POST</code> headers except those supported by the API. Amazon SageMaker might add additional headers. You should not rely on the behavior of headers outside those enumerated in the request syntax.</p> <p>Calls to <code>InvokeEndpointAsync</code> are authenticated by using Amazon Web Services Signature Version 4. For information, see <a href="https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html">Authenticating Requests (Amazon Web Services Signature Version 4)</a> in the <i>Amazon S3 API Reference</i>.</p> """,
    tags=['sagemaker_endpoint_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def invoke_endpoint_async(
    endpoint_name: constr(
        pattern=r'^[a-zA-Z0-9](-*[a-zA-Z0-9])*', max_length=63
    ) = Path(..., alias='EndpointName'),
    x__amzn__sage_maker__content__type: Optional[
        constr(pattern=r'\p{ASCII}*', max_length=1024)
    ] = Header(None, alias='X-Amzn-SageMaker-Content-Type'),
    x__amzn__sage_maker__accept: Optional[
        constr(pattern=r'\p{ASCII}*', max_length=1024)
    ] = Header(None, alias='X-Amzn-SageMaker-Accept'),
    x__amzn__sage_maker__custom__attributes: Optional[SecretStr] = Header(
        None, alias='X-Amzn-SageMaker-Custom-Attributes'
    ),
    x__amzn__sage_maker__inference__id: Optional[
        constr(pattern=r'\A\S[\p{Print}]*\z', min_length=1, max_length=64)
    ] = Header(None, alias='X-Amzn-SageMaker-Inference-Id'),
    x__amzn__sage_maker__input_location: constr(
        pattern=r'^(https|s3)://([^/]+)/?(.*)$', min_length=1, max_length=1024
    ) = Header(..., alias='X-Amzn-SageMaker-InputLocation'),
    x__amzn__sage_maker__request_t_t_l_seconds: Optional[
        conint(ge=60, le=21600)
    ] = Header(None, alias='X-Amzn-SageMaker-RequestTTLSeconds'),
    x__amzn__sage_maker__invocation_timeout_seconds: Optional[
        conint(ge=1, le=3600)
    ] = Header(None, alias='X-Amzn-SageMaker-InvocationTimeoutSeconds'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/endpoints/{EndpointName}/invocations',
    description=""" <p>After you deploy a model into production using Amazon SageMaker hosting services, your client applications use this API to get inferences from the model hosted at the specified endpoint. </p> <p>For an overview of Amazon SageMaker, see <a href="https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works.html">How It Works</a>. </p> <p>Amazon SageMaker strips all POST headers except those supported by the API. Amazon SageMaker might add additional headers. You should not rely on the behavior of headers outside those enumerated in the request syntax. </p> <p>Calls to <code>InvokeEndpoint</code> are authenticated by using Amazon Web Services Signature Version 4. For information, see <a href="https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html">Authenticating Requests (Amazon Web Services Signature Version 4)</a> in the <i>Amazon S3 API Reference</i>.</p> <p>A customer's model containers must respond to requests within 60 seconds. The model itself can have a maximum processing time of 60 seconds before responding to invocations. If your model is going to take 50-60 seconds of processing time, the SDK socket timeout should be set to be 70 seconds.</p> <note> <p>Endpoints are scoped to an individual account, and are not public. The URL does not contain the account ID, but Amazon SageMaker determines the account ID from the authentication token that is supplied by the caller.</p> </note> """,
    tags=['sagemaker_endpoint_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def invoke_endpoint(
    endpoint_name: constr(
        pattern=r'^[a-zA-Z0-9](-*[a-zA-Z0-9])*', max_length=63
    ) = Path(..., alias='EndpointName'),
    content__type: Optional[constr(pattern=r'\p{ASCII}*', max_length=1024)] = Header(
        None, alias='Content-Type'
    ),
    accept: Optional[constr(pattern=r'\p{ASCII}*', max_length=1024)] = Header(
        None, alias='Accept'
    ),
    x__amzn__sage_maker__custom__attributes: Optional[SecretStr] = Header(
        None, alias='X-Amzn-SageMaker-Custom-Attributes'
    ),
    x__amzn__sage_maker__target__model: Optional[
        constr(pattern=r'\A\S[\p{Print}]*\z', min_length=1, max_length=1024)
    ] = Header(None, alias='X-Amzn-SageMaker-Target-Model'),
    x__amzn__sage_maker__target__variant: Optional[
        constr(pattern=r'^[a-zA-Z0-9](-*[a-zA-Z0-9])*', max_length=63)
    ] = Header(None, alias='X-Amzn-SageMaker-Target-Variant'),
    x__amzn__sage_maker__target__container__hostname: Optional[
        constr(pattern=r'^[a-zA-Z0-9](-*[a-zA-Z0-9])*', max_length=63)
    ] = Header(None, alias='X-Amzn-SageMaker-Target-Container-Hostname'),
    x__amzn__sage_maker__inference__id: Optional[
        constr(pattern=r'\A\S[\p{Print}]*\z', min_length=1, max_length=64)
    ] = Header(None, alias='X-Amzn-SageMaker-Inference-Id'),
    x__amzn__sage_maker__enable__explanations: Optional[
        constr(pattern=r'.*', min_length=1, max_length=64)
    ] = Header(None, alias='X-Amzn-SageMaker-Enable-Explanations'),
    x__amz__content__sha256: Optional[str] = Header(None, alias='X-Amz-Content-Sha256'),
    x__amz__date: Optional[str] = Header(None, alias='X-Amz-Date'),
    x__amz__algorithm: Optional[str] = Header(None, alias='X-Amz-Algorithm'),
    x__amz__credential: Optional[str] = Header(None, alias='X-Amz-Credential'),
    x__amz__security__token: Optional[str] = Header(None, alias='X-Amz-Security-Token'),
    x__amz__signature: Optional[str] = Header(None, alias='X-Amz-Signature'),
    x__amz__signed_headers: Optional[str] = Header(None, alias='X-Amz-SignedHeaders'),
    body: EndpointsEndpointNameInvocationsPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
